# Generated by Django 2.0.7 on 2018-07-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='')),
                ('artist', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('title', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
        ),
    ]
