# Generated by Django 2.0.7 on 2018-07-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'verbose_name_plural': '음원 테이블'},
        ),
        migrations.AlterField(
            model_name='audio',
            name='artist',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='아티스트'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail/%Y/%m/%d', verbose_name='썸네일'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='타이틀'),
        ),
    ]
