# Generated by Django 2.0.7 on 2018-07-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_auto_20180721_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='max_bitrate',
            field=models.CharField(choices=[('320', 'High'), ('196', 'Mid'), ('128', 'Low')], default='Low', max_length=10, verbose_name='최대품질'),
        ),
    ]
