# Generated by Django 2.0.7 on 2018-07-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_audio_max_bitrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='audio',
            field=models.FileField(default=1, upload_to='audio/%Y/%m/%d', verbose_name='음원'),
            preserve_default=False,
        ),
    ]
